title: A Blog of Very Important Theories
author: Anne Elk
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is a blog of very important theories that are mine, Anne Elk, and what it is too. That's A-n-n-e Elk not "An elk."
  These are my theorys, which are mine, are mine. 

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
